# generated by datamodel-codegen:
#   filename:  error.json

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

ErrorClass: TypeAlias = Literal['api_connection', 'api_status', 'bad_request', 'authentication', 'permission_denied', 'not_found', 'conflict', 'unprocessable_entity', 'rate_limit', 'internal_server']


class ErrorBody(TypedDict):
    message: str
    type: str
    param: str | None
    code: str | None


OpenAiError = TypedDict(
    'OpenAiError',
    {
        'class': ErrorClass,
        'status': int | None,
        'headers': dict[str, str],
        'error': ErrorBody,
    },
)
