# generated by datamodel-codegen:
#   filename:  request.json

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired


class ChatCompletionRequestMessage(TypedDict):
    role: str
    content: str


class CreateChatCompletionRequest(TypedDict):
    model: str
    messages: list[ChatCompletionRequestMessage]
    temperature: NotRequired[float | None]
    max_tokens: NotRequired[int | None]
    top_p: NotRequired[float | None]
    stop: NotRequired[list[str] | None]
    stream: NotRequired[bool | None]
