# generated by datamodel-codegen:
#   filename:  response.json

from __future__ import annotations

from typing import TypeAlias, TypedDict

from typing_extensions import NotRequired


class TopLogprob(TypedDict):
    token: str
    bytes: list[int] | None
    logprob: float


class AnnotationURLCitation(TypedDict):
    end_index: int
    start_index: int
    title: str
    url: str


class ChatCompletionAudio(TypedDict):
    id: str
    data: str
    expires_at: int
    transcript: str


class FunctionCall(TypedDict):
    arguments: str
    name: str


class Function(TypedDict):
    arguments: str
    name: str


class Custom(TypedDict):
    input: str
    name: str


class ModerationResultBody(TypedDict):
    categories: dict[str, bool]
    category_applied_input_types: dict[str, list[str]]
    category_scores: dict[str, float]
    flagged: bool
    model: str
    type: str


class ChatCompletionModerationError(TypedDict):
    code: str
    message: str
    type: str


class CompletionTokensDetails(TypedDict):
    accepted_prediction_tokens: NotRequired[int]
    audio_tokens: NotRequired[int]
    reasoning_tokens: NotRequired[int]
    rejected_prediction_tokens: NotRequired[int]


class PromptTokensDetails(TypedDict):
    audio_tokens: NotRequired[int]
    cache_write_tokens: NotRequired[int]
    cached_tokens: NotRequired[int]


class ChatCompletionTokenLogprob(TypedDict):
    token: str
    bytes: list[int] | None
    logprob: float
    top_logprobs: list[TopLogprob]


class Annotation(TypedDict):
    type: str
    url_citation: AnnotationURLCitation


class ChatCompletionMessageToolCall(TypedDict):
    id: str
    type: str
    function: Function


class ChatCompletionMessageCustomToolCall(TypedDict):
    id: str
    type: str
    custom: Custom


class ChatCompletionModerationResults(TypedDict):
    model: str
    results: list[ModerationResultBody]
    type: str


class CompletionUsage(TypedDict):
    completion_tokens: int
    prompt_tokens: int
    total_tokens: int
    completion_tokens_details: NotRequired[CompletionTokensDetails]
    prompt_tokens_details: NotRequired[PromptTokensDetails]


class ChoiceLogprobs(TypedDict):
    content: NotRequired[list[ChatCompletionTokenLogprob]]
    refusal: NotRequired[list[ChatCompletionTokenLogprob]]


ChatCompletionMessageToolCallUnion: TypeAlias = ChatCompletionMessageToolCall | ChatCompletionMessageCustomToolCall


ModerationOutcome: TypeAlias = ChatCompletionModerationResults | ChatCompletionModerationError


class ChatCompletionResponseMessage(TypedDict):
    content: str | None
    refusal: str | None
    role: str
    annotations: NotRequired[list[Annotation]]
    audio: NotRequired[ChatCompletionAudio]
    function_call: NotRequired[FunctionCall]
    tool_calls: NotRequired[list[ChatCompletionMessageToolCallUnion]]


class ChatCompletionModeration(TypedDict):
    input: ModerationOutcome
    output: ModerationOutcome


class Choice(TypedDict):
    finish_reason: str
    index: int
    logprobs: NotRequired[ChoiceLogprobs]
    message: ChatCompletionResponseMessage


class CreateChatCompletionResponse(TypedDict):
    id: str
    choices: list[Choice]
    created: int
    model: str
    object: str
    moderation: NotRequired[ChatCompletionModeration]
    service_tier: NotRequired[str]
    system_fingerprint: NotRequired[str]
    usage: NotRequired[CompletionUsage]
