# generated by datamodel-codegen:
#   filename:  stream_response.json

from __future__ import annotations

from typing import TypeAlias, TypedDict

from typing_extensions import NotRequired


class DeltaFunctionCall(TypedDict):
    arguments: NotRequired[str]
    name: NotRequired[str]


class ToolCallChunkFunction(TypedDict):
    arguments: NotRequired[str]
    name: NotRequired[str]


class TopLogprob(TypedDict):
    token: str
    bytes: list[int] | None
    logprob: float


class ModerationResultBody(TypedDict):
    categories: dict[str, bool]
    category_applied_input_types: dict[str, list[str]]
    category_scores: dict[str, float]
    flagged: bool
    model: str
    type: str


class ChatCompletionModerationError(TypedDict):
    code: str
    message: str
    type: str


class CompletionTokensDetails(TypedDict):
    accepted_prediction_tokens: NotRequired[int]
    audio_tokens: NotRequired[int]
    reasoning_tokens: NotRequired[int]
    rejected_prediction_tokens: NotRequired[int]


class PromptTokensDetails(TypedDict):
    audio_tokens: NotRequired[int]
    cache_write_tokens: NotRequired[int]
    cached_tokens: NotRequired[int]


class ChatCompletionMessageToolCallChunk(TypedDict):
    index: int
    id: NotRequired[str]
    function: NotRequired[ToolCallChunkFunction]
    type: NotRequired[str]


class ChatCompletionTokenLogprob(TypedDict):
    token: str
    bytes: list[int] | None
    logprob: float
    top_logprobs: list[TopLogprob]


class ChatCompletionModerationResults(TypedDict):
    model: str
    results: list[ModerationResultBody]
    type: str


class CompletionUsage(TypedDict):
    completion_tokens: int
    prompt_tokens: int
    total_tokens: int
    completion_tokens_details: NotRequired[CompletionTokensDetails]
    prompt_tokens_details: NotRequired[PromptTokensDetails]


class ChatCompletionStreamResponseDelta(TypedDict):
    content: NotRequired[str | None]
    function_call: NotRequired[DeltaFunctionCall]
    refusal: NotRequired[str | None]
    role: NotRequired[str]
    tool_calls: NotRequired[list[ChatCompletionMessageToolCallChunk]]


class ChoiceLogprobs(TypedDict):
    content: NotRequired[list[ChatCompletionTokenLogprob] | None]
    refusal: NotRequired[list[ChatCompletionTokenLogprob] | None]


ModerationOutcome: TypeAlias = ChatCompletionModerationResults | ChatCompletionModerationError


class StreamChoice(TypedDict):
    delta: ChatCompletionStreamResponseDelta
    finish_reason: str | None
    index: int
    logprobs: NotRequired[ChoiceLogprobs | None]


class ChatCompletionModeration(TypedDict):
    input: ModerationOutcome
    output: ModerationOutcome


class CreateChatCompletionStreamResponse(TypedDict):
    id: str
    choices: list[StreamChoice]
    created: int
    model: str
    object: str
    moderation: NotRequired[ChatCompletionModeration | None]
    service_tier: NotRequired[str | None]
    system_fingerprint: NotRequired[str]
    usage: NotRequired[CompletionUsage | None]
